---
- name: Reboot hosts
  # Send the reboot command
  shell: sleep 2 && shutdown -r now
  become: yes
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: Wait for SSH port up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=15

- pause: seconds=30

  # Ping to the host until it returns
- name: ping for the host
  local_action: shell ansible -m ping {{ inventory_hostname }}
  register: ping_result

- name: Ping result
  debug: var=ping_result.stdout_lines
